### ISSUE TITLE
Ruby on Rails Group Project: Kanban Board

### ISSUE THREAD

**Issue by michael-duke** [michael-duke/Recipe-App#12]
## Good morning Reviewer 😄 ,

In this issue we have :
- Recognized that we are a group of 2 members (@michael-duke  and @samiullah997 ) 
- Created a Kanban board according to project [requirements](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/buisness_requirements.md)
- Assigned tasks that are individual and as a group
### Here is the link to our [Kanban setup](https://github.com/michael-duke/Recipe-App/projects/1)

**Comment by gemmen29** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💯 
- Descriptive info ✔️ 

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by michael-duke** [comment]
Thank you @gemmen29 for your review and feedback, and happy coding 😄 🚀
